ТЗ 13
AlishevAzamat/java-shareit pull request #1
Opened 2023-07-11 06:33 UTC by AlishevAzamat

2023-07-11 08:38 UTC, TomattmanYandex requested changes
Привет, комменты в коде

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/status/Status.java
> +package ru.practicum.shareit.booking.status;
1) при именовании пакетов по фичам, обычно не разбивают на множество подпакетов, только если что то прям выделяется, например у вас будет много dto их можно в отдельный пакет запихнуть
2) Status относится к модели данных, под него точно не надо отдельный пакет создавать

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +package ru.practicum.shareit.item.controller;
уже писал выше, но повторюсь, ри таком разбиении под пакеты для каждого типа сервисов пакеты не создают, все лежит в одном базовом

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public Item add(long id, Item item) {
лучше сделать чтобы сервис принимал и возвращал dto 
т.е. контроллер работает только с dto
сервис получает и возвращает dto но внутри себя предващает их в классы моделей и конр=тактирет с репозиторием
репозиторий работает только с классами моделей

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            updateName(item, itemDto);
кажется у вас по условию, поля должны обновляться только если они не null

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        validationId(id);
Зачем валидация id 
вызываем
itemRepository.getById(id); и записываем в переменную
Если результат null то кидаем ошибку, иначе просто возвращаем значение из переменной

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Item> items = new ArrayList<>();
в атких случаях обычно создают обработку в репозитории
в репозитории надо создать метод findByOwnerId и чтобы он возвращал только тех, у которых ownerId равен переданному параметру

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public ItemDto toItemDto(Item item) {
в маппеер также можно добавить перегруженный методы которые будут принимать список обьектов
и так можно будет этим не заморачиваться там где оно нынче делается,и никто кроме этого класса не будет отвечать за маппинг

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            for (Item item : itemRepository.getAll()) {
аналогично с пердыдущим, в репозитории следует создать метод findByText и всю эту логику закинуть туда

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            itemRepository.getById(id).isAvailable();
этот метод вообще выпилить нафиг

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            if (id < 0) {
отрицательный Id - валидный id если такого условия в тексте задачи не прописано, то не стоит так делать

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        try {
зачем работаь с ошибкой, если можно выполнить простую проверку
if (itemDto.getName() == null || itemDto.getName().isBlank()) {
//обновлять не надо, выходим из метода
return;
}
//действия по обновлению

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            if (!itemDto.getName().isBlank()) {
а еще условие isBlank выглядит некорректным, что делать если я хочу удалить значнеи поля?, сделать имя пустым?

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            log.error("Пустое поле");
пустое поле, и null поле это две разных вещи и два разных поведегния, пустое поле, может быть валидным значнеием, и нигде не прописано кстати что он не валдиное
а null это полное отсутствие значения

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        for (User user1 : userRepository.getAll()) {
следует сделать метод в репозитории который будет проверять существует ли email в базе (метод должен возвращать boolean) и делать проверку следующим образом - 
вызвал этот метод, если true кинуть оишбку если false работаем дальше

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        validationId(id);
про это уже писал

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private void validationId(long id) {
про это уже писал

2023-07-11 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +                for (User user1 : userRepository.getAll()) {
заметь снова есть логика по проверке всех емейлов, и дублируется полотно кода, а если был бы метод, которые это делает, то дублирования можно было бы избежать

2023-07-11 11:35 UTC, AlishevAzamat commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public Item add(long id, Item item) {
если я поменяю в сервисах на Dto то и репозиторий тоже нужно будет менять на Dto
так как репозиторий принимает Item

2023-07-12 04:45 UTC, AlishevAzamat commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        validationId(id);
Ну так валидация и делает ту проверку которую ты описываешь

2023-07-12 12:00 UTC, AlishevAzamat commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public ItemDto toItemDto(Item item) {
этого я не понял

2023-07-13 12:51 UTC, TomattmanYandex requested changes
Еще есть что переделать

2023-07-13 12:51 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    public List<Item> getAllByOwnerId(long id) {
зачем тут метод, который просто вызывает другой приватный метод?
почему содержимое приватного метода не поместить в этот, а сам приватный метод удалить

2023-07-13 12:51 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        if (str.isBlank()) {
это условие, лучше подошло бы уровню сервиса

2023-07-13 12:51 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +            for (Item item : items.values()) {
а тут стримы отлично подошли бы

2023-07-13 12:51 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        for (Item item : itemRepository.getAllByOwnerId(userId)) {
лучше сделать в маппере метод, который будет перегружить метод toItemDto но который будет принимать сразу список, а делать примерно то же что и тут, проходить по циклу, и вызывать для каждого метода метод который мапит один обьект
а тут уже вызывать метод который мапит сразу весь список (и кстати стримами тут можно тоже сделать)

2023-07-13 12:51 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public ItemDto toItemDto(Item item) {
у тебя есть метод public ItemDto toItemDto(Item item) 
делаем второй метод
public List<ItemDto> toItemDto(List<item> items)
его код будет примерно такой
return items.stream().map(item -> toItemDto(item)).toList()

и теперь если тебе надо смапить не один обьект а несколько сразу, то не надо будет в каждом месте писать этот цикл, а можно будет вызвать этот метод

таким образом получится что этот класс полностью отвечает только за маппинг, и больше никакой другой класс не будет отвечать за маппинг item

2023-07-13 12:51 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/User.java
> +    @NotBlank(message = "Имя не должно быть пустым.")
C класса моделей можно убрать валидацию

2023-07-13 12:51 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +            if (user.getEmail().equals(userDto.getEmail())) {
тут тоже можно стримами прописать

2023-07-14 09:22 UTC, TomattmanYandex approved these changes
Отлично, принято

2023-07-14 09:22 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public List<ItemDto> toItemDto(List<Item> items) {
Perfectamente (отлично)

2023-07-14 09:22 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +                .filter(item -> item.toString().toLowerCase().contains(str.toLowerCase()) && item.isAvailable())
можно было бы вынести в отдельный метод логику фильтрации, для легкого восприятия (но в этом случае не надо) так код читается легче порой

2023-07-17 04:04 UTC, merged