ТЗ-15
AlishevAzamat/java-shareit pull request #3
Opened 2023-08-10 06:22 UTC by AlishevAzamat

2023-08-10 09:24 UTC, TomattmanYandex requested changes
Есть вопросы по коду, и есть немного вопросов по тестам, смотри однотипные проблемы во всех тестах, плюс не вижу интеграционных тестов

2023-08-10 09:24 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Override
equals можно тоже сгенерировать ломбуком, с эксклюдом полей для сравнения

2023-08-10 09:24 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Override
а еще не лучший вариант сравнивать только по id учитывая что это поле может не прийти

2023-08-10 09:24 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Page<Booking> bookings;
лучше вынести создание pageble обьекта в отдельный метод. там присутствует логика, и если она изменится, то придётся делать это везде

2023-08-10 09:24 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        int pageNumber = (int) Math.ceil((double) from / size);
как то очень сложно, можно же гораздо проще

2023-08-10 09:24 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemDto.java
> +    Long requestId;
модификатор доступа

2023-08-10 09:24 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        int pageNumber = (int) Math.ceil((double) from / size);
про это я уже писал

2023-08-10 09:24 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    private final ItemRequestService service;
даже если один сервис, стоит дать ему нормальное имя

2023-08-10 09:24 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequestDto.java
> +    List<ItemDto> items;
модификатор доступа

2023-08-10 09:24 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    void createExceptionWhenAvailableIsFalse() {
тестовые методы именуем слудующим образом
имя метода_ что должен делать_при каких условиях
create_throwValidationsException_условие(я тут не понимаю почему ошибка должна упасть)

2023-08-10 09:24 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingTest.java
> +class BookingTest {
что этот тест делает?

2023-08-16 15:59 UTC, TomattmanYandex requested changes
Привет, все еще нету интеграционных тестов
интеграционные это те которые проверяет логику свззи различных слоев и компонентов (обычно тест сервиса или контроллера без моков репозитория, чтобы был использован реальный репозиторий, но  с тестовой базой)

2023-08-16 15:59 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private Page<Booking> createBookingPageForUser(long bookerId, State state, int from, int size) {
Я имелл ввиду другое
Сейчас у тебя в кждом методе PageRequest создается заново, а там есть логика высчитывания номера страницы,
если вдруг меняются требования, и например в параметре будет сразу приходить номер страницы, тогда тебе прийдется везде где создается PageRequest все переделывать
хорошим вариантом было бы создать в утильном классе утильный метод, который возвращал бы PageRequest а везде его уже использовать

2023-08-16 15:59 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        int pageNumber = (int) Math.ceil((double) from / size);
а ничего не решено))) я выше написал как лучше сделать

2023-08-21 17:00 UTC, AlishevAzamat commented
сделал все что смог 
прошу принять без критических замечаний

2023-08-22 08:15 UTC, TomattmanYandex approved these changes
Принято

2023-08-22 09:01 UTC, merged